### ISSUE TITLE
Unhandled 'error' event when trying to save

### ISSUE THREAD

**Issue by kepler** [jgdovin/meteor-html-pdf#2]
Just saw you added an option for (almost) directly serving the generated PDF to the client. I was just trying to make it work with a buffer (was getting an error). Unfortunately, it's still not working. I get the following at the server console:

```
W20150503-21:31:58.572(-3)? (STDERR) 
W20150503-21:31:58.573(-3)? (STDERR)         throw er; // Unhandled 'error' event
W20150503-21:31:58.573(-3)? (STDERR)               ^
W20150503-21:31:58.573(-3)? (STDERR) Error: spawn ENOENT
W20150503-21:31:58.573(-3)? (STDERR)     at errnoException (child_process.js:1011:11)
W20150503-21:31:58.573(-3)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
W20150503-21:31:58.573(-3)? (STDERR) events.js:72
```

I can dig a little deeper, if needed.

**Comment by jgdovin** [comment]
@kepler Thanks for reporting this. Do you have the code in a repo that I can clone and test this? Or a sample of the code so I can try to reproduce this.

**Comment by kepler** [comment]
I've just set up clock sample project and added your package and a use case: https://github.com/kepler/meteor-clock-test-pdf

When I click the button, I get the error mentioned above plus this one (on the server console):
`[Error: This socket is closed.]`

The server then restarts automatically.

At the same time, on the client console I get:
`Exception in delivering result of invoking 'pdfCollection': TypeError: Cannot read property 'pdf' of undefined`

However, this seems like a consequence of the earlier error.

I tracked it down to this line (`helpers.js:118`), but couldn't go any further:
`var result = fn.apply(self, newArgs);`

Everything worked when I installed your package locally (inside `packages/`) and also when I copy-pasted your code directly inside the project.

May be an issue with using both bindEnvironment and wrapSync. [Seems like the first is not necessary when using the second](https://www.discovermeteor.com/blog/wrapping-npm-packages/).

Finally, might be worth saying I'm running this on Windows. I'll try running on Linux later and will get back here if something different happens.

**Comment by kepler** [comment]
OK, so I've tested the clock project in a Linux environment and got the same error. So I forked your project and removed the calls to `bindEnvironment`. To avoid the case where it worked when installed locally, I published it to atmosphere and then added it to the clock project (after removing your package). And it worked. And it's actually working much faster; earlier, there was a 5 seconds delay between clicking and receiving the save dialog.

I'll try to test it a little more, but if you think this fixes the issue, please let me know and I'll submit a PR and remove my copy from atmosphere.

**Comment by jgdovin** [comment]
go ahead and submit a PR and I will test this in a couple environments. I appreciate you taking the time to track this down.

**Comment by purplecones** [comment]
Hi, I'm getting the same issue. I have the following code executed on a button click:

```
Meteor.pdf.save($scope.document.content, $scope.document.name);
```

document.content contains a html string which is a lengthy document. When I do your example

```
Meteor.pdf.save('<h1>My Cool Pdf</h1>', 'myFileName');
```

it works fine. But not when I pass $scope.document.content. Any thoughts on how to resolve this?

**Comment by manybothans** [comment]
Getting similar issue. Has this been resolved for anyone?

Works perfectly on local machine, but on Galaxy I'm getting: 

```
[Error: html-pdf: Unknown Error]
Error: write EPIPE
 at errnoException (net.js:905:11)
 at Object.afterWrite (net.js:721:19)
```

I'm using it in server-only code like this:

``` javascript
pdf.create(html, {
    "format": "Letter",
    "orientation": "landscape",
}).toBuffer(Meteor.bindEnvironment(function(err, buffer) {
    if(err)
        return console.log(err);

    var attachments = [{
        fileName: "NewFile.pdf",
        contents: buffer
    }];

    // Email PDF ...
}));
```
